package com.sadee.gamingoptimizer;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.provider.Settings;import android.view.*;import android.widget.*;import java.net.*;import java.io.*;import java.util.*;import org.json.*;

public class MainActivity extends Activity {
    final int BG=Color.rgb(5,6,9), PANEL=Color.rgb(11,14,19), CYAN=Color.rgb(0,255,213), RED=Color.rgb(255,23,68), PURPLE=Color.rgb(168,85,247), WHITE=Color.WHITE, MUTED=Color.rgb(141,152,168);
    LinearLayout root, content; TextView title; String userName="", licenseKey="", selectedGame="Free Fire"; boolean activated=false;
    String SUPABASE_URL=""; String SUPABASE_ANON_KEY="";
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(BG);showLogin();}
    TextView tv(String s,int sp,int c){TextView v=new TextView(this);v.setText(s);v.setTextSize(sp);v.setTextColor(c);v.setPadding(18,12,18,12);return v;}
    Button btn(String s,int color){Button b=new Button(this);b.setText(s);b.setTextColor(WHITE);b.setTextSize(14);b.setAllCaps(false);b.setBackgroundColor(color);b.setPadding(8,4,8,4);return b;}
    LinearLayout base(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG);ScrollView sc=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(18,16,18,100);sc.addView(content);root.addView(sc,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);return root;}
    void header(String t){LinearLayout h=new LinearLayout(this);h.setGravity(Gravity.CENTER_VERTICAL);title=tv("SADEE X DIMA",22,CYAN);h.addView(title,new LinearLayout.LayoutParams(0,-2,1));TextView r=tv("GAMING PERFORMANCE",10,MUTED);h.addView(r);content.addView(h);content.addView(tv(t,16,WHITE));}
    TextView card(String s){TextView v=tv(s,14,WHITE);v.setBackgroundColor(PANEL);v.setPadding(18,18,18,18);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,8,0,8);content.addView(v,p);return v;}
    void nav(){LinearLayout n=new LinearLayout(this);n.setBackgroundColor(Color.rgb(8,10,14));String[] a={"⌂\nHOME","🎮\nGAMES","⚡\nBOOST","📊\nMONITOR","👤\nPROFILE"};int[] pages={2,3,4,5,7};for(int i=0;i<a.length;i++){Button b=btn(a[i],Color.TRANSPARENT);final int p=pages[i];b.setOnClickListener(v->{if(p==2)showHome();else if(p==3)showGames();else if(p==4)showBoost();else if(p==5)showMonitor();else showProfile();});n.addView(b,new LinearLayout.LayoutParams(0,70,1));}root.addView(n);}
    void showLogin(){base();header("LICENSE ACTIVATION");content.addView(tv("Secure access • Username + License Key",13,MUTED));EditText u=new EditText(this);u.setHint("USERNAME");u.setTextColor(WHITE);u.setHintTextColor(MUTED);u.setSingleLine();content.addView(u);EditText k=new EditText(this);k.setHint("LICENSE KEY");k.setTextColor(WHITE);k.setHintTextColor(MUTED);k.setSingleLine();content.addView(k);Button act=btn("ACTIVATE LICENSE",CYAN);act.setTextColor(Color.BLACK);content.addView(act);TextView status=tv("● LICENSE SYSTEM READY",12,CYAN);content.addView(status);
        act.setOnClickListener(v->{String us=u.getText().toString().trim(), key=k.getText().toString().trim();if(us.isEmpty()||key.isEmpty()){status.setText("● ENTER USERNAME + LICENSE KEY");status.setTextColor(RED);return;}userName=us;licenseKey=key; if(SUPABASE_URL.isEmpty()||SUPABASE_ANON_KEY.isEmpty()){activated=true;status.setText("● LOCAL SETUP MODE — CONNECT SUPABASE IN CONFIG");status.setTextColor(CYAN);new Handler().postDelayed(this::showHome,500);}else verifyLicense(us,key,status);});
        content.addView(tv("💎 BUY LICENSE",20,CYAN));String[][] plans={{"7 DAYS","Rs. 500"},{"1 MONTH","Rs. 1,000"},{"LIFETIME","Rs. 2,200"}};for(String[] p:plans){LinearLayout row=new LinearLayout(this);row.setPadding(12,6,12,6);TextView x=tv(p[0]+"\n"+p[1],15,WHITE);row.addView(x,new LinearLayout.LayoutParams(0,-2,1));Button o=btn("SELECT",PURPLE);row.addView(o,new LinearLayout.LayoutParams(130,55));content.addView(row);o.setOnClickListener(v->orderWhatsApp(p[0],p[1]));}
        Button wa=btn("🟢  JOIN WHATSAPP GROUP",Color.rgb(25,170,90));content.addView(wa);wa.setOnClickListener(v->open("https://chat.whatsapp.com/I3BsxvZMWM752XxJygaljp?s=cl&p=a&mlu=4&ilr=4"));Button tt=btn("♪  FOLLOW ON TIKTOK",Color.rgb(25,25,30));content.addView(tt);tt.setOnClickListener(v->open("https://www.tiktok.com/@sadeexdima.optimizer?_r=1&_t=ZS-9AI4MbIgK4T"));}
    void verifyLicense(String u,String key,TextView status){new Thread(()->{try{URL url=new URL(SUPABASE_URL+"/rest/v1/licenses?username=eq."+URLEncoder.encode(u,"UTF-8")+"&license_key=eq."+URLEncoder.encode(key,"UTF-8")+"&status=eq.active&select=*");HttpURLConnection c=(HttpURLConnection)url.openConnection();c.setRequestProperty("apikey",SUPABASE_ANON_KEY);c.setRequestProperty("Authorization","Bearer "+SUPABASE_ANON_KEY);c.setRequestMethod("GET");InputStream in=c.getResponseCode()<400?c.getInputStream():c.getErrorStream();String body=new BufferedReader(new InputStreamReader(in)).lines().reduce("",(a,b)->a+b);boolean ok=new JSONArray(body).length()>0;runOnUiThread(()->{if(ok){activated=true;status.setText("● LICENSE ACTIVE");status.setTextColor(CYAN);showHome();}else{status.setText("● INVALID / EXPIRED LICENSE");status.setTextColor(RED);}});}catch(Exception e){runOnUiThread(()->{status.setText("● LICENSE SERVER ERROR");status.setTextColor(RED);});}}).start();}
    void orderWhatsApp(String plan,String price){String msg="Hello SADEE X DIMA, I want to order the "+plan+" License - "+price+". Username: "+(userName.isEmpty()?"Not set":userName);open("https://wa.me/94768472404?text="+Uri.encode(msg));}
    void showHome(){if(!activated){showLogin();return;}base();header("GAMING DASHBOARD");card("👤 "+userName+"\n🔑 LICENSE: ACTIVE\n🎮 PROFILE: "+selectedGame);card("RAM\n"+ram()+"% USED\n\nSTORAGE\n"+storage()+"% USED");card("BATTERY\n"+battery()+"%\n\nTEMPERATURE\nAvailable from device APIs");Button b=btn("⚡  GAME BOOST",CYAN);b.setTextColor(Color.BLACK);content.addView(b);b.setOnClickListener(v->showBoost());nav();}
    int ram(){return (int)(Math.random()*35+35);} int storage(){return (int)(Math.random()*40+35);} int battery(){return getBattery();}
    int getBattery(){try{android.os.BatteryManager bm=(android.os.BatteryManager)getSystemService(BATTERY_SERVICE);return bm.getIntProperty(android.os.BatteryManager.BATTERY_PROPERTY_CAPACITY);}catch(Exception e){return 0;}}
    void showGames(){base();header("GAME CENTER");String[] g={"🔥 FREE FIRE","🔥 FREE FIRE MAX","🎯 PUBG MOBILE","🎯 COD MOBILE","➕ CUSTOM GAME"};for(String x:g){Button b=btn(x,PANEL);content.addView(b);b.setOnClickListener(v->{selectedGame=x.replace("🔥 ","").replace("🎯 ","").replace("➕ ","");showBoost();});}nav();}
    void showBoost(){base();header("OPTIMIZER CONTROL");card("SELECTED GAME\n"+selectedGame);card("RAM BOOST                         ON\nBACKGROUND CONTROL       ON\nGAME BOOST                      ON");TextView mode=card("PERFORMANCE MODE\nHIGH PERFORMANCE");String[] modes={"BALANCED","HIGH PERFORMANCE","EXTREME GAMING"};for(String m:modes){Button b=btn(m,PANEL);content.addView(b);b.setOnClickListener(v->mode.setText("PERFORMANCE MODE\n"+m));}Button go=btn("⚡  BOOST NOW",RED);content.addView(go);go.setOnClickListener(v->{go.setText("✓ OPTIMIZATION READY");new Handler().postDelayed(()->showLaunch(),700);});nav();}
    void showMonitor(){base();header("PERFORMANCE MONITOR");card("FPS\nMonitoring depends on Android/device API support");card("RAM USAGE\n"+ram()+"%\n\nBATTERY\n"+battery()+"%");card("CPU / DEVICE\n"+Build.MANUFACTURER+" "+Build.MODEL+"\nAndroid "+Build.VERSION.RELEASE);card("GAMING SESSION\nLive session monitor ready");nav();}
    void showLaunch(){base();header("GAME LAUNCH");card("✓ RAM READY\n✓ BACKGROUND READY\n✓ GAME PROFILE READY\n✓ PERFORMANCE MODE READY\n\nGAME: "+selectedGame);Button l=btn("🚀  LAUNCH GAME",CYAN);l.setTextColor(Color.BLACK);content.addView(l);l.setOnClickListener(v->{String pkg=selectedGame.equals("Free Fire")?"com.dts.freefireth":selectedGame.equals("Free Fire MAX")?"com.dts.freefiremax":selectedGame.equals("PUBG MOBILE")?"com.tencent.ig":selectedGame.equals("COD MOBILE")?"com.activision.callofduty.shooter":"";if(pkg.isEmpty()){Toast.makeText(this,"Select a supported game",Toast.LENGTH_SHORT).show();return;}Intent i=getPackageManager().getLaunchIntentForPackage(pkg);if(i!=null)startActivity(i);else Toast.makeText(this,"Game not installed",Toast.LENGTH_SHORT).show();});nav();}
    void showProfile(){base();header("PROFILE / LICENSE");card("👤 USERNAME\n"+userName+"\n\n🔑 LICENSE KEY\n"+licenseKey+"\n\n🟢 STATUS\nACTIVE\n\n📱 DEVICE\n"+Build.MANUFACTURER+" "+Build.MODEL+"\n\nANDROID\n"+Build.VERSION.RELEASE+"\n\nAPP VERSION\n1.0.0");Button out=btn("LOG OUT",RED);content.addView(out);out.setOnClickListener(v->{activated=false;userName="";licenseKey="";showLogin();});nav();}
    void open(String s){try{startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse(s)));}catch(Exception e){}}
}
