/* SADEE X DIMA GAMING ADMIN - no-login build */
const SUPABASE_URL='https://cpmzjplfqggmgeotmtcd.supabase.co';
const SUPABASE_KEY='sb_publishable_z0kmWe85ybkmBg7bzEtyKA_kMH6WGXW';
const db=window.supabase?.createClient(SUPABASE_URL,SUPABASE_KEY)||null;
const PAGES=['Dashboard','License Keys','Devices / Users','Game Profiles','Optimizer Controls','App Updates','Pro Analytics','Security Center','Product Editor','Settings'];
let keys=[],devicesData=[],gamesData=[],settingsData=null;
const $=id=>document.getElementById(id);
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function toast(msg,error=false){const x=$('toast');x.textContent=msg;x.className='toast show '+(error?'error':'');setTimeout(()=>x.className='toast',2600)}
function apiError(r){return r?.error?.message||'Supabase request failed';}
function nav(){const n=$('nav');n.innerHTML='';PAGES.forEach(p=>{const b=document.createElement('button');b.textContent=p;b.dataset.page=p;b.onclick=()=>go(p);n.appendChild(b)});}
function go(p){location.hash=encodeURIComponent(p);render(p);document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===p));window.scrollTo(0,0)}
function currentPage(){try{return decodeURIComponent(location.hash.slice(1))||'Dashboard'}catch{return 'Dashboard'}}
function render(p){$('title').textContent=p; if(!db){$('page').innerHTML='<div class="card red"><h2>Supabase configuration error</h2><p>The bundled Supabase URL/key could not be initialized. Check internet access and the Supabase JS CDN.</p></div>';return} if(p==='Dashboard')dashboard();else if(p==='License Keys')license();else if(p==='Devices / Users')devices();else if(p==='Game Profiles')games();else if(p==='Optimizer Controls')optimizer();else if(p==='App Updates')updates();else if(p==='Pro Analytics')analytics();else if(p==='Security Center')security();else if(p==='Product Editor')products();else settings();}
async function dashboard(){
 $('page').innerHTML=`<div class="grid"><div class="card cyan stat"><b>LICENSE KEYS</b><h2 id="kc">...</h2></div><div class="card purple stat"><b>ACTIVE KEYS</b><h2 id="ac">...</h2></div><div class="card red stat"><b>REGISTERED DEVICES</b><h2 id="dc">...</h2></div><div class="card cyan stat"><b>ONLINE / RECENT</b><h2 id="rc">...</h2></div></div><div class="card cyan hero-admin"><div class="hero-kicker">SADEE × DIMA • GAMING ADMIN PRO</div><h2>⚡ COMMAND CENTER</h2><p class="meta">Manage licenses, device limits, game profiles, optimizer controls, app releases and Pro tools from one futuristic control center.</p></div><div class="grid"><button class="quick cyan" onclick="go('License Keys')">🔑 LICENSE MANAGER</button><button class="quick purple" onclick="go('Devices / Users')">📱 DEVICES / USERS</button><button class="quick red" onclick="go('Optimizer Controls')">⚡ OPTIMIZER</button><button class="quick cyan" onclick="go('Pro Analytics')">📊 PRO ANALYTICS</button></div>`;
 const a=await db.from('license_keys').select('status');if(!a.error){$('kc').textContent=a.data.length;$('ac').textContent=a.data.filter(x=>x.status==='active').length}else toast(apiError(a),true);
 const d=await db.from('license_devices').select('id,last_active_at');if(!d.error){$('dc').textContent=d.data.length;$('rc').textContent=d.data.filter(x=>Date.now()-new Date(x.last_active_at||0).getTime()<15*60*1000).length;}
}
function license(){
 $('page').innerHTML='<div class="card cyan"><h2>🔑 Add / Generate License</h2><div class="form"><input id="nk" placeholder="KEY (blank = generate)"><input id="nu" placeholder="USERNAME"><select id="np"><option value="7">7 DAYS — Rs.500</option><option value="30">1 MONTH — Rs.1,000</option><option value="life">LIFETIME — Rs.2,200</option><option value="custom">CUSTOM EXPIRY</option></select><input id="ne" type="date"><select id="nd"><option value="1">1 DEVICE</option><option value="2">2 DEVICES</option><option value="3">3 DEVICES</option><option value="5">5 DEVICES</option><option value="999">UNLIMITED</option></select><select id="ns"><option>active</option><option>disabled</option><option>revoked</option></select></div><button class="primary" onclick="addKey()">SAVE / GENERATE KEY</button></div><div class="toolbar"><input id="q" placeholder="Search key / user" oninput="drawKeys()"><button onclick="loadKeys()">REFRESH</button></div><div id="cards" class="cards"></div>';loadKeys();}
function makeKey(){const r=()=>Math.random().toString(36).slice(2,7).toUpperCase();return `SDX-${r()}-${r()}-${r()}`}
async function addKey(){try{const plan=$('np').value,key=$('nk').value.trim()||makeKey();let exp=null;if(plan==='7'||plan==='30'){const d=new Date();d.setDate(d.getDate()+Number(plan));exp=d.toISOString()}else if(plan==='custom'&&$('ne').value)exp=new Date($('ne').value+'T23:59:59').toISOString();const durationDays=plan==='7'?7:plan==='30'?30:0;const payload={key_code:key,username:$('nu').value.trim()||null,plan,status:$('ns').value,expires_at:exp,duration_days:durationDays,device_limit:Number($('nd').value)};const r=await db.from('license_keys').insert(payload);if(r.error)throw r.error;toast('License saved: '+key);loadKeys()}catch(e){toast(e.message||String(e),true)}}
async function loadKeys(){const box=$('cards');if(box)box.innerHTML='<div class="card">Loading licenses...</div>';const r=await db.from('license_keys').select('*').order('created_at',{ascending:false});if(r.error){if(box)box.innerHTML='<div class="card red">'+esc(r.error.message)+'</div>';return}const d=await db.from('license_devices').select('license_key_id,id');const counts={};if(!d.error)(d.data||[]).forEach(x=>{counts[x.license_key_id]=(counts[x.license_key_id]||0)+1});keys=(r.data||[]).map(k=>({...k,device_count:counts[k.id]||0}));drawKeys()}
function drawKeys(){const box=$('cards');if(!box)return;const q=($('q')?.value||'').toLowerCase();const arr=keys.filter(k=>(k.key_code||'').toLowerCase().includes(q)||(k.username||'').toLowerCase().includes(q));box.innerHTML=arr.map(k=>`<article class="keycard"><div class="key">🔑 ${esc(k.key_code)}</div><div class="meta">👤 USER: ${esc(k.username||'Not assigned')}<br>💳 PLAN: ${esc(k.plan||'—')}<br>⏳ EXPIRES: ${k.expires_at?esc(new Date(k.expires_at).toLocaleString()):'Lifetime'}<br>👥 DEVICES: ${esc(k.device_count||0)} / ${k.device_limit>=999?'Unlimited':esc(k.device_limit||1)}<br>🟢 STATUS: ${esc(k.status||'—')}</div><div class="actions"><button onclick="statusKey('${k.id}','active')">ACTIVATE</button><button onclick="statusKey('${k.id}','disabled')">DISABLE</button><button onclick="statusKey('${k.id}','revoked')">REVOKE</button><button onclick="resetDevice('${k.id}')">RESET DEVICES</button></div></article>`).join('')||'<div class="card">No keys found.</div>'}
async function statusKey(id,status){const r=await db.from('license_keys').update({status,updated_at:new Date().toISOString()}).eq('id',id);if(r.error)toast(r.error.message,true);else{toast('License updated');loadKeys()}}
async function resetDevice(id){const r=await db.from('license_devices').delete().eq('license_key_id',id);if(r.error)toast(r.error.message,true);else{toast('Device binding reset');loadKeys()}}
async function devices(){
 $('page').innerHTML='<div class="card cyan"><h2>📱 Devices / Users</h2><p class="meta">Live device records submitted by the optimizer app.</p></div><div class="toolbar"><input id="dq" placeholder="Search device / username / key" oninput="drawDevices()"><button onclick="devices()">REFRESH</button></div><div id="deviceCards" class="cards"></div>';const r=await db.from('license_devices').select('*,license_keys(key_code,username,status,expires_at)').order('last_active_at',{ascending:false});if(r.error){$('deviceCards').innerHTML='<div class="card red">'+esc(r.error.message)+'</div>';return}devicesData=r.data||[];drawDevices()}
function drawDevices(){const box=$('deviceCards');if(!box)return;const q=($('dq')?.value||'').toLowerCase();const arr=devicesData.filter(d=>JSON.stringify(d).toLowerCase().includes(q));box.innerHTML=arr.map(d=>`<article class="card purple"><h3>📱 ${esc(d.device_name||'Unknown device')}</h3><div class="meta">👤 USER: ${esc(d.license_keys?.username||'—')}<br>🔑 KEY: ${esc(d.license_keys?.key_code||'—')}<br>📱 DEVICE ID: ${esc(d.device_id||'—')}<br>🤖 ANDROID: ${esc(d.android_version||'—')}<br>🧠 RAM: ${esc(d.ram||'—')}<br>💾 STORAGE: ${esc(d.storage||'—')}<br>⚙️ CPU: ${esc(d.cpu||'—')}<br>🟢 FIRST: ${esc(d.first_activated_at||'—')}<br>🕒 LAST ACTIVE: ${esc(d.last_active_at||'—')}</div><button onclick="deleteDevice('${d.id}')">RESET THIS DEVICE</button></article>`).join('')||'<div class="card">No devices found.</div>'}
async function deleteDevice(id){const r=await db.from('license_devices').delete().eq('id',id);if(r.error)toast(r.error.message,true);else{toast('Device reset');devices()}}
async function games(){
 $('page').innerHTML='<div class="card cyan"><h2>🎮 Game Profiles</h2><p class="meta">Enable/disable games and set performance mode. Changes are stored in Supabase.</p></div><div id="gameCards" class="grid"></div>';const r=await db.from('game_profiles').select('*').order('game_name');if(r.error){$('gameCards').innerHTML='<div class="card red">'+esc(r.error.message)+'</div>';return}gamesData=r.data||[];const names=['Free Fire','Free Fire MAX','PUBG Mobile','COD Mobile','Custom Game'];for(const name of names)if(!gamesData.some(g=>g.game_name===name)){const ins=await db.from('game_profiles').insert({game_name:name,enabled:true,performance_mode:'high'}).select().single();if(!ins.error)gamesData.push(ins.data)}drawGames()}
function drawGames(){const box=$('gameCards');box.innerHTML=gamesData.map((g,i)=>`<article class="card ${['cyan','purple','red'][i%3]}"><h2>🎮 ${esc(g.game_name)}</h2><label class="switchrow"><input id="en-${g.id}" type="checkbox" ${g.enabled?'checked':''}> ENABLED</label><select id="mode-${g.id}"><option value="balanced" ${g.performance_mode==='balanced'?'selected':''}>BALANCED</option><option value="high" ${g.performance_mode==='high'?'selected':''}>HIGH PERFORMANCE</option><option value="extreme" ${g.performance_mode==='extreme'?'selected':''}>EXTREME GAMING</option></select><button onclick="saveGame('${g.id}',document.getElementById('en-${g.id}')?.checked??${!!g.enabled},document.getElementById('mode-${g.id}').value)">SAVE PROFILE</button></article>`).join('')}
async function saveGame(id,enabled,mode){const r=await db.from('game_profiles').update({enabled,performance_mode:mode}).eq('id',id);if(r.error)toast(r.error.message,true);else toast('Game profile saved')}
async function optimizer(){
 const r=await db.from('optimizer_settings').select('*').order('key');let vals={performance_mode:'high',ram_boost:true,background_control:true,game_boost:true};if(!r.error)r.data.forEach(x=>{try{vals[x.key]=typeof x.value==='string'?JSON.parse(x.value):x.value}catch{vals[x.key]=x.value}});
 $('page').innerHTML=`<div class="card cyan"><h2>⚡ Optimizer Controls</h2><div class="form"><select id="om"><option value="balanced">Balanced</option><option value="high">High Performance</option><option value="extreme">Extreme Gaming</option></select><label class="check"><input id="ram" type="checkbox" ${vals.ram_boost?'checked':''}> RAM Boost</label><label class="check"><input id="bg" type="checkbox" ${vals.background_control?'checked':''}> Background Control</label><label class="check"><input id="gb" type="checkbox" ${vals.game_boost?'checked':''}> Game Boost</label></div><button class="primary" onclick="saveOptimizer()">SAVE OPTIMIZER SETTINGS</button></div>`;$('om').value=vals.performance_mode||'high'}
async function saveOptimizer(){const rows=[['performance_mode',$('om').value],['ram_boost',$('ram').checked],['background_control',$('bg').checked],['game_boost',$('gb').checked]];for(const [key,value] of rows){const r=await db.from('optimizer_settings').upsert({key,value:JSON.stringify(value)},{onConflict:'key'});if(r.error){toast(r.error.message,true);return}}toast('Optimizer settings saved')}
async function updates(){const r=await db.from('app_updates').select('*').order('created_at',{ascending:false});const rows=r.error?[]:r.data||[];$('page').innerHTML=`<div class="card purple"><h2>📦 App Updates</h2><div class="form"><input id="uv" placeholder="Version e.g. 2.2.0"><input id="ua" placeholder="APK URL"><input id="um" placeholder="Update message"><label class="check"><input id="uf" type="checkbox"> Force update</label><label class="check"><input id="ua2" type="checkbox" checked> Active</label></div><button class="primary" onclick="saveUpdate()">SAVE UPDATE</button></div><div class="cards">${rows.map(x=>`<article class="card"><h3>v${esc(x.version)}</h3><div class="meta">${esc(x.message||'')}<br>${esc(x.apk_url||'')}<br>Force: ${x.force_update?'YES':'NO'} • Active: ${x.active?'YES':'NO'}</div></article>`).join('')}</div>`}
async function saveUpdate(){const r=await db.from('app_updates').insert({version:$('uv').value.trim(),apk_url:$('ua').value.trim(),message:$('um').value.trim(),force_update:$('uf').checked,active:$('ua2').checked});if(r.error)toast(r.error.message,true);else{toast('Update saved');updates()}}
async function settings(){const r=await db.from('app_settings').select('*').limit(1).maybeSingle();settingsData=r.data||{app_name:'SADEE X DIMA',whatsapp:'+94 76 847 2404',whatsapp_group:'https://chat.whatsapp.com/I3BsxvZMWM752XxJygaljp?s=cl&p=a&mlu=4&ilr=4',tiktok:'https://www.tiktok.com/@sadeexdima.optimizer?_r=1&_t=ZS-9AI4MbIgK4T',price_7d:500,price_1m:1000,price_lifetime:2200,announcement:'',maintenance:false};$('page').innerHTML=`<div class="card cyan"><h2>⚙️ Remote Settings</h2><div class="form"><input id="sa" value="${esc(settingsData.app_name)}" placeholder="App name"><input id="sw" value="${esc(settingsData.whatsapp)}" placeholder="WhatsApp"><input id="sg" value="${esc(settingsData.whatsapp_group)}" placeholder="WhatsApp group"><input id="st" value="${esc(settingsData.tiktok)}" placeholder="TikTok"><input id="p7" type="number" value="${esc(settingsData.price_7d)}" placeholder="7 day price"><input id="p1" type="number" value="${esc(settingsData.price_1m)}" placeholder="1 month price"><input id="pl" type="number" value="${esc(settingsData.price_lifetime)}" placeholder="Lifetime price"><input id="ann" value="${esc(settingsData.announcement||'')}" placeholder="Announcement"><label class="check"><input id="maint" type="checkbox" ${settingsData.maintenance?'checked':''}> Maintenance mode</label></div><button class="primary" onclick="saveSettings()">SAVE SETTINGS</button></div>`}
async function saveSettings(){const data={app_name:$('sa').value,whatsapp:$('sw').value,whatsapp_group:$('sg').value,tiktok:$('st').value,price_7d:Number($('p7').value),price_1m:Number($('p1').value),price_lifetime:Number($('pl').value),announcement:$('ann').value,maintenance:$('maint').checked,updated_at:new Date().toISOString()};let existing=await db.from('app_settings').select('id').limit(1).maybeSingle();let r;if(existing.data?.id) r=await db.from('app_settings').update(data).eq('id',existing.data.id); else r=await db.from('app_settings').insert(data);if(r.error)toast(r.error.message,true);else toast('Settings saved')}
async function analytics(){
 const [k,d]=await Promise.all([db.from('license_keys').select('*'),db.from('license_devices').select('*')]);
 const keysA=k.error?[]:k.data||[], devA=d.error?[]:d.data||[];
 const active=keysA.filter(x=>x.status==='active').length, limits=keysA.reduce((a,x)=>a+Number(x.device_limit||0),0);
 $('page').innerHTML=`<div class="card cyan"><h2>📊 PRO ANALYTICS</h2><p class="meta">Live statistics derived from your current Supabase license and device data.</p></div><div class="grid"><div class="card cyan stat"><b>TOTAL LICENSES</b><h2>${keysA.length}</h2></div><div class="card purple stat"><b>ACTIVE</b><h2>${active}</h2></div><div class="card red stat"><b>DEVICES</b><h2>${devA.length}</h2></div><div class="card cyan stat"><b>DEVICE CAPACITY</b><h2>${limits>=999?'∞':limits}</h2></div></div><div class="card purple"><h3>⚡ RECENT DEVICE ACTIVITY</h3><div class="meta">${devA.slice().sort((a,b)=>new Date(b.last_active_at||0)-new Date(a.last_active_at||0)).slice(0,8).map(x=>`<div class="activity-row">📱 ${esc(x.device_name||'Unknown')} <span>${esc(x.last_active_at||'—')}</span></div>`).join('')||'No device activity yet.'}</div></div>`;
}
async function security(){
 const r=await db.from('license_devices').select('id,device_id,device_name,android_version,last_active_at,license_keys(username,key_code,status)');const rows=r.error?[]:r.data||[];
 $('page').innerHTML=`<div class="card red"><h2>🛡️ SECURITY CENTER</h2><p class="meta">Review active device bindings and license status. Resetting a device removes its current binding.</p></div><div class="cards">${rows.map(x=>`<article class="card"><h3>📱 ${esc(x.device_name||'Unknown')}</h3><div class="meta">USER: ${esc(x.license_keys?.username||'—')}<br>KEY: ${esc(x.license_keys?.key_code||'—')}<br>DEVICE ID: ${esc(x.device_id||'—')}<br>ANDROID: ${esc(x.android_version||'—')}<br>LAST ACTIVE: ${esc(x.last_active_at||'—')}</div><button onclick="deleteDevice('${x.id}')">RESET DEVICE</button></article>`).join('')||'<div class="card">No device records.</div>'}</div>`;
}
function products(){
 $('page').innerHTML=`<div class="card cyan"><h2>🛒 PRODUCT EDITOR / NEW</h2><p class="meta">Create a product record for your store. This Pro editor is kept separate from the existing license system.</p><div class="form"><input id="pn" placeholder="Product name"><input id="pc" placeholder="Category"><input id="pp" type="number" placeholder="Price (LKR)"><input id="pv" placeholder="Version"><input id="pu" placeholder="Download URL"><input id="pi" placeholder="Product image URL"><textarea id="pd" placeholder="Description" rows="4"></textarea><textarea id="pf" placeholder="Features — one per line" rows="6"></textarea><label class="check"><input id="pfeat" type="checkbox"> Featured</label><label class="check"><input id="pvis" type="checkbox" checked> Visible</label><label class="check"><input id="pen" type="checkbox" checked> Download enabled</label><label class="check"><input id="pkey" type="checkbox"> Requires paid key</label></div><button class="primary" onclick="saveProduct()">SAVE PRODUCT</button></div><div id="productList" class="cards"></div>`;loadProducts();
}
async function loadProducts(){const box=$('productList');if(!box)return;const r=await db.from('products').select('*').order('created_at',{ascending:false});if(r.error){box.innerHTML='<div class="card red">Products table not installed yet. Run the supplied PRO migration SQL.</div>';return}box.innerHTML=(r.data||[]).map(x=>`<article class="card purple"><h3>📦 ${esc(x.name)}</h3><div class="meta">${esc(x.category||'—')} • Rs. ${esc(x.price_lkr??'0')}<br>v${esc(x.version||'—')}<br>${esc(x.description||'')}</div></article>`).join('')||'<div class="card">No products yet.</div>'}
async function saveProduct(){const payload={name:$('pn').value.trim(),category:$('pc').value.trim(),price_lkr:Number($('pp').value||0),version:$('pv').value.trim(),download_url:$('pu').value.trim(),image_url:$('pi').value.trim(),description:$('pd').value.trim(),features:$('pf').value.split('\\n').map(x=>x.trim()).filter(Boolean),featured:$('pfeat').checked,visible:$('pvis').checked,download_enabled:$('pen').checked,requires_paid_key:$('pkey').checked};if(!payload.name){toast('Product name required',true);return}const r=await db.from('products').insert(payload);if(r.error)toast(r.error.message,true);else{toast('Product saved');products()}}
window.addEventListener('hashchange',()=>render(currentPage()));window.addEventListener('DOMContentLoaded',()=>{nav();go(currentPage());setInterval(()=>{$('clock').textContent=new Date().toLocaleString()},1000);$('clock').textContent=new Date().toLocaleString()});
